name: Build .dylib

on:
  push:
    branches:
      - master  # 触发构建的分支

jobs:
  build:
    runs-on: macOS-latest  # 使用 macOS 环境构建

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: 'latest'  # 使用最新版本的 Xcode

      - name: Compile .dylib
        run: |
          set -e  # 在任何命令失败时终止构建
          # 使用 find 命令寻找 .mm, .m 和 .cpp 文件
          source_files=$(find src -name '*.mm' -o -name '*.m' -o -name '*.cpp')
          
          # 编译动态库
          clang++ -dynamiclib -o libmylibrary.dylib $source_files -Iinclude -fobjc-arc
          
      - name: Upload .dylib
        uses: actions/upload-artifact@v2
        with:
          name: mylibrary
          path: libmylibrary.dylib
